# Generated by Django 4.2.6 on 2023-11-02 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=150)),
                ('Password', models.CharField(blank=True, max_length=128)),
                ('confirm_pass', models.CharField(blank=True, max_length=128)),
            ],
        ),
    ]
